version: '3.4'

services:
  db:
    build:
      context: .
    env_file:
      - './.env'
    networks:
      - backend
    ports:
      - '5432:5432'
    volumes:
      - './data/pgdata:/var/lib/postgresql/data/casting'
    restart: always

networks:
  backend: